apiVersion: v1
kind: Service
metadata:
  name: service-api-produto
  labels:
    name: lbl-api-produto
spec:
  selector:
    name: lbl-api-produto
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30091
  type: NodePort
  #type: ClusterIP